export const COLORS = {
    BLUE: '#031D53', 
    ORANG: '#FF6D00', 
    LIGTH_GRAY: '#f1eeee', 
    DARK_GRAY: '#939393', 
};
export const COUNTRY_LIST = {
    "+93":{"name":"Afghanistan","flag":"🇦🇫","code":"AF"},
    "+358":{"name":"Åland Islands","flag":"🇦🇽","code":"AX"},
    "+355":{"name":"Albania","flag":"🇦🇱","code":"AL"},
    "+213":{"name":"Algeria","flag":"🇩🇿","code":"DZ"},
    "+1684":{"name":"American Samoa","flag":"🇦🇸","code":"AS"},
    "+376":{"name":"Andorra","flag":"🇦🇩","code":"AD"},
    "+244":{"name":"Angola","flag":"🇦🇴","code":"AO"},
    "+1264":{"name":"Anguilla","flag":"🇦🇮","code":"AI"},
    "+672":{"name":"Antarctica","flag":"🇦🇶","code":"AQ"},
    "+1268":{"name":"Antigua and Barbuda","flag":"🇦🇬","code":"AG"},
    "+54":{"name":"Argentina","flag":"🇦🇷","code":"AR"},
    "+374":{"name":"Armenia","flag":"🇦🇲","code":"AM"},
    "+297":{"name":"Aruba","flag":"🇦🇼","code":"AW"},
    "+61":{"name":"Australia","flag":"🇦🇺","code":"AU"},
    "+43":{"name":"Austria","flag":"🇦🇹","code":"AT"},
    "+994":{"name":"Azerbaijan","flag":"🇦🇿","code":"AZ"},
    "+1242":{"name":"Bahamas","flag":"🇧🇸","code":"BS"},
    "+973":{"name":"Bahrain","flag":"🇧🇭","code":"BH"},
    "+880":{"name":"Bangladesh","flag":"🇧🇩","code":"BD"},
    "+1246":{"name":"Barbados","flag":"🇧🇧","code":"BB"},
    "+375":{"name":"Belarus","flag":"🇧🇾","code":"BY"},
    "+32":{"name":"Belgium","flag":"🇧🇪","code":"BE"},
    "+501":{"name":"Belize","flag":"🇧🇿","code":"BZ"},
    "+229":{"name":"Benin","flag":"🇧🇯","code":"BJ"},
    "+1441":{"name":"Bermuda","flag":"🇧🇲","code":"BM"},
    "+975":{"name":"Bhutan","flag":"🇧🇹","code":"BT"},
    "+591":{"name":"Bolivia, Plurinational State of bolivia","flag":"🇧🇴","code":"BO"},
    "+387":{"name":"Bosnia and Herzegovina","flag":"🇧🇦","code":"BA"},
    "+267":{"name":"Botswana","flag":"🇧🇼","code":"BW"},
    "+47":{"name":"Bouvet Island","flag":"🇧🇻","code":"BV"},
    "+55":{"name":"Brazil","flag":"🇧🇷","code":"BR"},
    "+246":{"name":"British Indian Ocean Territory","flag":"🇮🇴","code":"IO"},
    "+673":{"name":"Brunei Darussalam","flag":"🇧🇳","code":"BN"},
    "+359":{"name":"Bulgaria","flag":"🇧🇬","code":"BG"},
    "+226":{"name":"Burkina Faso","flag":"🇧🇫","code":"BF"},
    "+257":{"name":"Burundi","flag":"🇧🇮","code":"BI"},
    "+855":{"name":"Cambodia","flag":"🇰🇭","code":"KH"},
    "+237":{"name":"Cameroon","flag":"🇨🇲","code":"CM"},
    "+238":{"name":"Cape Verde","flag":"🇨🇻","code":"CV"},
    "+345":{"name":"Cayman Islands","flag":"🇰🇾","code":"KY"},
    "+236":{"name":"Central African Republic","flag":"🇨🇫","code":"CF"},
    "+235":{"name":"Chad","flag":"🇹🇩","code":"TD"},
    "+56":{"name":"Chile","flag":"🇨🇱","code":"CL"},
    "+86":{"name":"China","flag":"🇨🇳","code":"CN"},
    "+61":{"name":"Christmas Island","flag":"🇨🇽","code":"CX"},
    "+61":{"name":"Cocos (Keeling) Islands","flag":"🇨🇨","code":"CC"},
    "+57":{"name":"Colombia","flag":"🇨🇴","code":"CO"},
    "+269":{"name":"Comoros","flag":"🇰🇲","code":"KM"},
    "+242":{"name":"Congo","flag":"🇨🇬","code":"CG"},
    "+243":{"name":"Congo, The Democratic Republic of the Congo","flag":"🇨🇩","code":"CD"},
    "+682":{"name":"Cook Islands","flag":"🇨🇰","code":"CK"},
    "+506":{"name":"Costa Rica","flag":"🇨🇷","code":"CR"},
    "+225":{"name":"Cote d'Ivoire","flag":"🇨🇮","code":"CI"},
    "+385":{"name":"Croatia","flag":"🇭🇷","code":"HR"},
    "+53":{"name":"Cuba","flag":"🇨🇺","code":"CU"},
    "+357":{"name":"Cyprus","flag":"🇨🇾","code":"CY"},
    "+420":{"name":"Czech Republic","flag":"🇨🇿","code":"CZ"},
    "+45":{"name":"Denmark","flag":"🇩🇰","code":"DK"},
    "+253":{"name":"Djibouti","flag":"🇩🇯","code":"DJ"},
    "+1767":{"name":"Dominica","flag":"🇩🇲","code":"DM"},
    "+1849":{"name":"Dominican Republic","flag":"🇩🇴","code":"DO"},
    "+593":{"name":"Ecuador","flag":"🇪🇨","code":"EC"},
    "+20":{"name":"Egypt","flag":"🇪🇬","code":"EG"},
    "+503":{"name":"El Salvador","flag":"🇸🇻","code":"SV"},
    "+240":{"name":"Equatorial Guinea","flag":"🇬🇶","code":"GQ"},
    "+291":{"name":"Eritrea","flag":"🇪🇷","code":"ER"},
    "+372":{"name":"Estonia","flag":"🇪🇪","code":"EE"},
    "+251":{"name":"Ethiopia","flag":"🇪🇹","code":"ET"},
    "+500":{"name":"Falkland Islands (Malvinas)","flag":"🇫🇰","code":"FK"},
    "+298":{"name":"Faroe Islands","flag":"🇫🇴","code":"FO"},
    "+679":{"name":"Fiji","flag":"🇫🇯","code":"FJ"},
    "+358":{"name":"Finland","flag":"🇫🇮","code":"FI"},
    "+33":{"name":"France","flag":"🇫🇷","code":"FR"},
    "+594":{"name":"French Guiana","flag":"🇬🇫","code":"GF"},
    "+689":{"name":"French Polynesia","flag":"🇵🇫","code":"PF"},
    "+262":{"name":"French Southern Territories","flag":"🇹🇫","code":"TF"},
    "+241":{"name":"Gabon","flag":"🇬🇦","code":"GA"},
    "+220":{"name":"Gambia","flag":"🇬🇲","code":"GM"},
    "+995":{"name":"Georgia","flag":"🇬🇪","code":"GE"},
    "+49":{"name":"Germany","flag":"🇩🇪","code":"DE"},
    "+233":{"name":"Ghana","flag":"🇬🇭","code":"GH"},
    "+350":{"name":"Gibraltar","flag":"🇬🇮","code":"GI"},
    "+30":{"name":"Greece","flag":"🇬🇷","code":"GR"},
    "+299":{"name":"Greenland","flag":"🇬🇱","code":"GL"},
    "+1473":{"name":"Grenada","flag":"🇬🇩","code":"GD"},
    "+590":{"name":"Guadeloupe","flag":"🇬🇵","code":"GP"},
    "+1671":{"name":"Guam","flag":"🇬🇺","code":"GU"},
    "+502":{"name":"Guatemala","flag":"🇬🇹","code":"GT"},
    "+44":{"name":"Guernsey","flag":"🇬🇬","code":"GG"},
    "+224":{"name":"Guinea","flag":"🇬🇳","code":"GN"},
    "+245":{"name":"Guinea-Bissau","flag":"🇬🇼","code":"GW"},
    "+592":{"name":"Guyana","flag":"🇬🇾","code":"GY"},
    "+509":{"name":"Haiti","flag":"🇭🇹","code":"HT"},
    "+672":{"name":"Heard Island and Mcdonald Islands","flag":"🇭🇲","code":"HM"},
    "+379":{"name":"Holy See (Vatican City State)","flag":"🇻🇦","code":"VA"},
    "+504":{"name":"Honduras","flag":"🇭🇳","code":"HN"},
    "+852":{"name":"Hong Kong","flag":"🇭🇰","code":"HK"},
    "+36":{"name":"Hungary","flag":"🇭🇺","code":"HU"},
    "+354":{"name":"Iceland","flag":"🇮🇸","code":"IS"},
    "+91":{"name":"India","flag":"🇮🇳","code":"IN"},
    "+62":{"name":"Indonesia","flag":"🇮🇩","code":"ID"},
    "+98":{"name":"Iran, Islamic Republic of Persian Gulf","flag":"🇮🇷","code":"IR"},
    "+964":{"name":"Iraq","flag":"🇮🇶","code":"IQ"},
    "+353":{"name":"Ireland","flag":"🇮🇪","code":"IE"},
    "+44":{"name":"Isle of Man","flag":"🇮🇲","code":"IM"},
    "+972":{"name":"Israel","flag":"🇮🇱","code":"IL"},
    "+39":{"name":"Italy","flag":"🇮🇹","code":"IT"},
    "+1876":{"name":"Jamaica","flag":"🇯🇲","code":"JM"},
    "+81":{"name":"Japan","flag":"🇯🇵","code":"JP"},
    "+962":{"name":"Jordan","flag":"🇯🇴","code":"JO"},
    "+7":{"name":"Kazakhstan","flag":"🇰🇿","code":"KZ"},
    "+254":{"name":"Kenya","flag":"🇰🇪","code":"KE"},
    "+686":{"name":"Kiribati","flag":"🇰🇮","code":"KI"},
    "+850":{"name":"Korea, Democratic People's Republic of Korea","flag":"🇰🇵","code":"KP"},
    "+82":{"name":"Korea, Republic of South Korea","flag":"🇰🇷","code":"KR"},
    "+383":{"name":"Kosovo","flag":"🇽🇰","code":"XK"},
    "+965":{"name":"Kuwait","flag":"🇰🇼","code":"KW"},
    "+996":{"name":"Kyrgyzstan","flag":"🇰🇬","code":"KG"},
    "+856":{"name":"Laos","flag":"🇱🇦","code":"LA"},
    "+371":{"name":"Latvia","flag":"🇱🇻","code":"LV"},
    "+961":{"name":"Lebanon","flag":"🇱🇧","code":"LB"},
    "+266":{"name":"Lesotho","flag":"🇱🇸","code":"LS"},
    "+231":{"name":"Liberia","flag":"🇱🇷","code":"LR"},
    "+218":{"name":"Libyan Arab Jamahiriya","flag":"🇱🇾","code":"LY"},
    "+423":{"name":"Liechtenstein","flag":"🇱🇮","code":"LI"},
    "+370":{"name":"Lithuania","flag":"🇱🇹","code":"LT"},
    "+352":{"name":"Luxembourg","flag":"🇱🇺","code":"LU"},
    "+853":{"name":"Macao","flag":"🇲🇴","code":"MO"},
    "+389":{"name":"Macedonia","flag":"🇲🇰","code":"MK"},
    "+261":{"name":"Madagascar","flag":"🇲🇬","code":"MG"},
    "+265":{"name":"Malawi","flag":"🇲🇼","code":"MW"},
    "+60":{"name":"Malaysia","flag":"🇲🇾","code":"MY"},
    "+960":{"name":"Maldives","flag":"🇲🇻","code":"MV"},
    "+223":{"name":"Mali","flag":"🇲🇱","code":"ML"},
    "+356":{"name":"Malta","flag":"🇲🇹","code":"MT"},
    "+692":{"name":"Marshall Islands","flag":"🇲🇭","code":"MH"},
    "+596":{"name":"Martinique","flag":"🇲🇶","code":"MQ"},
    "+222":{"name":"Mauritania","flag":"🇲🇷","code":"MR"},
    "+230":{"name":"Mauritius","flag":"🇲🇺","code":"MU"},
    "+262":{"name":"Mayotte","flag":"🇾🇹","code":"YT"},
    "+52":{"name":"Mexico","flag":"🇲🇽","code":"MX"},
    "+691":{"name":"Micronesia, Federated States of Micronesia","flag":"🇫🇲","code":"FM"},
    "+373":{"name":"Moldova","flag":"🇲🇩","code":"MD"},
    "+377":{"name":"Monaco","flag":"🇲🇨","code":"MC"},
    "+976":{"name":"Mongolia","flag":"🇲🇳","code":"MN"},
    "+382":{"name":"Montenegro","flag":"🇲🇪","code":"ME"},
    "+1664":{"name":"Montserrat","flag":"🇲🇸","code":"MS"},
    "+212":{"name":"Morocco","flag":"🇲🇦","code":"MA"},
    "+258":{"name":"Mozambique","flag":"🇲🇿","code":"MZ"},
    "+95":{"name":"Myanmar","flag":"🇲🇲","code":"MM"},
    "+264":{"name":"Namibia","flag":"🇳🇦","code":"NA"},
    "+674":{"name":"Nauru","flag":"🇳🇷","code":"NR"},
    "+977":{"name":"Nepal","flag":"🇳🇵","code":"NP"},
    "+31":{"name":"Netherlands","flag":"🇳🇱","code":"NL"},
    "+599":{"name":"Netherlands Antilles","flag":"","code":"AN"},
    "+687":{"name":"New Caledonia","flag":"🇳🇨","code":"NC"},
    "+64":{"name":"New Zealand","flag":"🇳🇿","code":"NZ"},
    "+505":{"name":"Nicaragua","flag":"🇳🇮","code":"NI"},
    "+227":{"name":"Niger","flag":"🇳🇪","code":"NE"},
    "+234":{"name":"Nigeria","flag":"🇳🇬","code":"NG"},
    "+683":{"name":"Niue","flag":"🇳🇺","code":"NU"},
    "+672":{"name":"Norfolk Island","flag":"🇳🇫","code":"NF"},
    "+1670":{"name":"Northern Mariana Islands","flag":"🇲🇵","code":"MP"},
    "+47":{"name":"Norway","flag":"🇳🇴","code":"NO"},
    "+968":{"name":"Oman","flag":"🇴🇲","code":"OM"},
    "+92":{"name":"Pakistan","flag":"🇵🇰","code":"PK"},
    "+680":{"name":"Palau","flag":"🇵🇼","code":"PW"},
    "+970":{"name":"Palestinian Territory, Occupied","flag":"🇵🇸","code":"PS"},
    "+507":{"name":"Panama","flag":"🇵🇦","code":"PA"},
    "+675":{"name":"Papua New Guinea","flag":"🇵🇬","code":"PG"},
    "+595":{"name":"Paraguay","flag":"🇵🇾","code":"PY"},
    "+51":{"name":"Peru","flag":"🇵🇪","code":"PE"},
    "+63":{"name":"Philippines","flag":"🇵🇭","code":"PH"},
    "+64":{"name":"Pitcairn","flag":"🇵🇳","code":"PN"},
    "+48":{"name":"Poland","flag":"🇵🇱","code":"PL"},
    "+351":{"name":"Portugal","flag":"🇵🇹","code":"PT"},
    "+1939":{"name":"Puerto Rico","flag":"🇵🇷","code":"PR"},
    "+974":{"name":"Qatar","flag":"🇶🇦","code":"QA"},
    "+40":{"name":"Romania","flag":"🇷🇴","code":"RO"},
    "+7":{"name":"Russia","flag":"🇷🇺","code":"RU"},
    "+250":{"name":"Rwanda","flag":"🇷🇼","code":"RW"},
    "+262":{"name":"Reunion","flag":"🇷🇪","code":"RE"},
    "+590":{"name":"Saint Barthelemy","flag":"🇧🇱","code":"BL"},
    "+290":{"name":"Saint Helena, Ascension and Tristan Da Cunha","flag":"🇸🇭","code":"SH"},
    "+1869":{"name":"Saint Kitts and Nevis","flag":"🇰🇳","code":"KN"},
    "+1758":{"name":"Saint Lucia","flag":"🇱🇨","code":"LC"},
    "+590":{"name":"Saint Martin","flag":"🇲🇫","code":"MF"},
    "+508":{"name":"Saint Pierre and Miquelon","flag":"🇵🇲","code":"PM"},
    "+1784":{"name":"Saint Vincent and the Grenadines","flag":"🇻🇨","code":"VC"},
    "+685":{"name":"Samoa","flag":"🇼🇸","code":"WS"},
    "+378":{"name":"San Marino","flag":"🇸🇲","code":"SM"},
    "+239":{"name":"Sao Tome and Principe","flag":"🇸🇹","code":"ST"},
    "+966":{"name":"Saudi Arabia","flag":"🇸🇦","code":"SA"},
    "+221":{"name":"Senegal","flag":"🇸🇳","code":"SN"},
    "+381":{"name":"Serbia","flag":"🇷🇸","code":"RS"},
    "+248":{"name":"Seychelles","flag":"🇸🇨","code":"SC"},
    "+232":{"name":"Sierra Leone","flag":"🇸🇱","code":"SL"},
    "+65":{"name":"Singapore","flag":"🇸🇬","code":"SG"},
    "+421":{"name":"Slovakia","flag":"🇸🇰","code":"SK"},
    "+386":{"name":"Slovenia","flag":"🇸🇮","code":"SI"},
    "+677":{"name":"Solomon Islands","flag":"🇸🇧","code":"SB"},
    "+252":{"name":"Somalia","flag":"🇸🇴","code":"SO"},
    "+27":{"name":"South Africa","flag":"🇿🇦","code":"ZA"},
    "+211":{"name":"South Sudan","flag":"🇸🇸","code":"SS"},
    "+500":{"name":"South Georgia and the South Sandwich Islands","flag":"🇬🇸","code":"GS"},
    "+34":{"name":"Spain","flag":"🇪🇸","code":"ES"},
    "+94":{"name":"Sri Lanka","flag":"🇱🇰","code":"LK"},
    "+249":{"name":"Sudan","flag":"🇸🇩","code":"SD"},
    "+597":{"name":"Suriname","flag":"🇸🇷","code":"SR"},
    "+47":{"name":"Svalbard and Jan Mayen","flag":"🇸🇯","code":"SJ"},
    "+268":{"name":"Eswatini","flag":"🇸🇿","code":"SZ"},
    "+46":{"name":"Sweden","flag":"🇸🇪","code":"SE"},
    "+41":{"name":"Switzerland","flag":"🇨🇭","code":"CH"},
    "+963":{"name":"Syrian Arab Republic","flag":"🇸🇾","code":"SY"},
    "+886":{"name":"Taiwan","flag":"🇹🇼","code":"TW"},
    "+992":{"name":"Tajikistan","flag":"🇹🇯","code":"TJ"},
    "+255":{"name":"Tanzania, United Republic of Tanzania","flag":"🇹🇿","code":"TZ"},
    "+66":{"name":"Thailand","flag":"🇹🇭","code":"TH"},
    "+670":{"name":"Timor-Leste","flag":"🇹🇱","code":"TL"},
    "+228":{"name":"Togo","flag":"🇹🇬","code":"TG"},
    "+690":{"name":"Tokelau","flag":"🇹🇰","code":"TK"},
    "+676":{"name":"Tonga","flag":"🇹🇴","code":"TO"},
    "+1868":{"name":"Trinidad and Tobago","flag":"🇹🇹","code":"TT"},
    "+216":{"name":"Tunisia","flag":"🇹🇳","code":"TN"},
    "+90":{"name":"Turkey","flag":"🇹🇷","code":"TR"},
    "+993":{"name":"Turkmenistan","flag":"🇹🇲","code":"TM"},
    "+1649":{"name":"Turks and Caicos Islands","flag":"🇹🇨","code":"TC"},
    "+688":{"name":"Tuvalu","flag":"🇹🇻","code":"TV"},
    "+256":{"name":"Uganda","flag":"🇺🇬","code":"UG"},
    "+380":{"name":"Ukraine","flag":"🇺🇦","code":"UA"},
    "+971":{"name":"United Arab Emirates","flag":"🇦🇪","code":"AE"},
    "+44":{"name":"United Kingdom","flag":"🇬🇧","code":"GB"},
    "+1":{"name":"United States","flag":"🇺🇸","code":"US"},
    "+598":{"name":"Uruguay","flag":"🇺🇾","code":"UY"},
    "+998":{"name":"Uzbekistan","flag":"🇺🇿","code":"UZ"},
    "+678":{"name":"Vanuatu","flag":"🇻🇺","code":"VU"},
    "+58":{"name":"Venezuela, Bolivarian Republic of Venezuela","flag":"🇻🇪","code":"VE"},
    "+84":{"name":"Vietnam","flag":"🇻🇳","code":"VN"},
    "+1284":{"name":"Virgin Islands, British","flag":"🇻🇬","code":"VG"},
    "+1340":{"name":"Virgin Islands, U.S.","flag":"🇻🇮","code":"VI"},
    "+681":{"name":"Wallis and Futuna","flag":"🇼🇫","code":"WF"},
    "+967":{"name":"Yemen","flag":"🇾🇪","code":"YE"},
    "+260":{"name":"Zambia","flag":"🇿🇲","code":"ZM"},
    "+263":{"name":"Zimbabwe","flag":"🇿🇼","code":"ZW"}
};

